
GET http://0.0.0.0:8080/graduate_student/3
Accept: application/json

###
GET http://0.0.0.0:8080/graduate_student/2021/Бизнес-информатика
Accept: application/json

###
GET http://0.0.0.0:8080/api/login
Accept: application/json